services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '9901:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - postgres
    postgres:
        image: 'postgres:15'
        ports:
            - '9902:5432'
        environment:
            POSTGRES_DB: 'water'
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: '12345'
        volumes:
            - 'sail-postgres:/var/lib/postgresql/data'
            - './docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "admin"]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-postgres:
        driver: local
